name: AutoCIS

on:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]   

  schedule:
    - cron: 30 14 * * *

jobs: 

  AutoCIS:
    runs-on: windows-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright

      - name: Ensure browsers are installed
        run: python -m playwright install

      - name: Run python script
        env:
            INFO: ${{ secrets.INFO }}
        run: python hfut_lite.py 
